version: '3.9'

services:
  ms-payments:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-payments-app
    container_name: ms-payments
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}

      - SPRING_DATASOURCE_URL=jdbc:postgresql://payments-db:5432/${DB_NAME:-payments}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-admin}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS:-123456}

      - SPRING_FLYWAY_URL=jdbc:postgresql://payments-db:5432/${DB_NAME:-payments}
      - SPRING_FLYWAY_USER=${DB_USER:-admin}
      - SPRING_FLYWAY_PASSWORD=${DB_PASS:-123456}
    depends_on:
      payments-db:
        condition: service_healthy
    networks:
      - soat-net
    ports:
      - "8082:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  payments-db:
    image: postgres:17-alpine
    container_name: payments-db
    environment:
      - POSTGRES_DB=${DB_NAME:-payments}
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASS:-123456}
    ports:
      - "5434:5432"
    networks:
      - soat-net
    volumes:
      - payments-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-payments}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  soat-net:
    name: soat-net
    driver: bridge

volumes:
  payments-data:
    name: payments-data
