apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmaps/payments-app.yml
  - secrets/payments-app.yml
  - deployments/payments-app.yml
  - services/payments-app.yml
  - hpa/payments-app.yml
