apiVersion: v1
kind: Service
metadata:
  name: payments-app
  namespace: payments
spec:
  type: LoadBalancer
  selector:
    app: payments-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
